/*
 * CloneCord API
 * REST API to use CloneCord
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Channel', 'model/Member', 'model/Role'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Channel'), require('./Member'), require('./Role'));
  } else {
    // Browser globals (root is window)
    if (!root.CloneCordApi) {
      root.CloneCordApi = {};
    }
    root.CloneCordApi.Guild = factory(root.CloneCordApi.ApiClient, root.CloneCordApi.Channel, root.CloneCordApi.Member, root.CloneCordApi.Role);
  }
}(this, function(ApiClient, Channel, Member, Role) {
  'use strict';

  /**
   * The Guild model module.
   * @module model/Guild
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Guild</code>.
   * @alias module:model/Guild
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Guild</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Guild} obj Optional instance to populate.
   * @return {module:model/Guild} The populated <code>Guild</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('channels'))
        obj.channels = ApiClient.convertToType(data['channels'], [Channel]);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('members'))
        obj.members = ApiClient.convertToType(data['members'], [Member]);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], [Role]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Channel>} channels
   */
  exports.prototype.channels = undefined;

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Array.<module:model/Member>} members
   */
  exports.prototype.members = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Array.<module:model/Role>} roles
   */
  exports.prototype.roles = undefined;

  return exports;

}));
