/*
 * CloneCord API
 * REST API to use CloneCord
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Reaction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Reaction'));
  } else {
    // Browser globals (root is window)
    if (!root.CloneCordApi) {
      root.CloneCordApi = {};
    }
    root.CloneCordApi.Message = factory(root.CloneCordApi.ApiClient, root.CloneCordApi.Reaction);
  }
}(this, function(ApiClient, Reaction) {
  'use strict';

  /**
   * The Message model module.
   * @module model/Message
   * @version 1.0
   */

  /**
   * Constructs a new <code>Message</code>.
   * @alias module:model/Message
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Message} obj Optional instance to populate.
   * @return {module:model/Message} The populated <code>Message</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('channelId'))
        obj.channelId = ApiClient.convertToType(data['channelId'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('reactionList'))
        obj.reactionList = ApiClient.convertToType(data['reactionList'], [Reaction]);
      if (data.hasOwnProperty('senderId'))
        obj.senderId = ApiClient.convertToType(data['senderId'], 'String');
      if (data.hasOwnProperty('sentDate'))
        obj.sentDate = ApiClient.convertToType(data['sentDate'], 'Date');
    }
    return obj;
  }

  /**
   * @member {String} channelId
   */
  exports.prototype.channelId = undefined;

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {Array.<module:model/Reaction>} reactionList
   */
  exports.prototype.reactionList = undefined;

  /**
   * @member {String} senderId
   */
  exports.prototype.senderId = undefined;

  /**
   * @member {Date} sentDate
   */
  exports.prototype.sentDate = undefined;

  return exports;

}));
