/**
 * CloneCord API
 * REST API to use CloneCord
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Reaction from './Reaction';

/**
 * The Message model module.
 * @module model/Message
 * @version 1.0.1
 */
class Message {
    /**
     * Constructs a new <code>Message</code>.
     * @alias module:model/Message
     * @param message {String} 
     */
    constructor(message) { 
        
        Message.initialize(this, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message) { 
        obj['message'] = message;
    }

    /**
     * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Message} obj Optional instance to populate.
     * @return {module:model/Message} The populated <code>Message</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Message();

            if (data.hasOwnProperty('channelId')) {
                obj['channelId'] = ApiClient.convertToType(data['channelId'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('reactionList')) {
                obj['reactionList'] = ApiClient.convertToType(data['reactionList'], [Reaction]);
            }
            if (data.hasOwnProperty('senderId')) {
                obj['senderId'] = ApiClient.convertToType(data['senderId'], 'String');
            }
            if (data.hasOwnProperty('sentDate')) {
                obj['sentDate'] = ApiClient.convertToType(data['sentDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} channelId
 */
Message.prototype['channelId'] = undefined;

/**
 * @member {String} id
 */
Message.prototype['id'] = undefined;

/**
 * @member {String} message
 */
Message.prototype['message'] = undefined;

/**
 * @member {Array.<module:model/Reaction>} reactionList
 */
Message.prototype['reactionList'] = undefined;

/**
 * @member {String} senderId
 */
Message.prototype['senderId'] = undefined;

/**
 * @member {Date} sentDate
 */
Message.prototype['sentDate'] = undefined;






export default Message;

