/**
 * CloneCord API
 * REST API to use CloneCord
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Reaction model module.
 * @module model/Reaction
 * @version 1.0.1
 */
class Reaction {
    /**
     * Constructs a new <code>Reaction</code>.
     * @alias module:model/Reaction
     * @param authorUuid {String} 
     * @param emoteId {Number} 
     */
    constructor(authorUuid, emoteId) { 
        
        Reaction.initialize(this, authorUuid, emoteId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, authorUuid, emoteId) { 
        obj['authorUuid'] = authorUuid;
        obj['emoteId'] = emoteId;
    }

    /**
     * Constructs a <code>Reaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Reaction} obj Optional instance to populate.
     * @return {module:model/Reaction} The populated <code>Reaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Reaction();

            if (data.hasOwnProperty('authorUuid')) {
                obj['authorUuid'] = ApiClient.convertToType(data['authorUuid'], 'String');
            }
            if (data.hasOwnProperty('emoteId')) {
                obj['emoteId'] = ApiClient.convertToType(data['emoteId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} authorUuid
 */
Reaction.prototype['authorUuid'] = undefined;

/**
 * @member {Number} emoteId
 */
Reaction.prototype['emoteId'] = undefined;






export default Reaction;

