/*
 * CloneCord API
 * REST API to use CloneCord
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloneCordApi) {
      root.CloneCordApi = {};
    }
    root.CloneCordApi.Reaction = factory(root.CloneCordApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Reaction model module.
   * @module model/Reaction
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>Reaction</code>.
   * @alias module:model/Reaction
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Reaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reaction} obj Optional instance to populate.
   * @return {module:model/Reaction} The populated <code>Reaction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('authorUuid'))
        obj.authorUuid = ApiClient.convertToType(data['authorUuid'], 'String');
      if (data.hasOwnProperty('emoteId'))
        obj.emoteId = ApiClient.convertToType(data['emoteId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} authorUuid
   */
  exports.prototype.authorUuid = undefined;

  /**
   * @member {Number} emoteId
   */
  exports.prototype.emoteId = undefined;

  return exports;

}));
