/*
 * CloneCord API
 * REST API to use CloneCord
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RegistrationUser', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/RegistrationUser'), require('../model/User'));
  } else {
    // Browser globals (root is window)
    if (!root.CloneCordApi) {
      root.CloneCordApi = {};
    }
    root.CloneCordApi.AuthControllerApi = factory(root.CloneCordApi.ApiClient, root.CloneCordApi.RegistrationUser, root.CloneCordApi.User);
  }
}(this, function(ApiClient, RegistrationUser, User) {
  'use strict';

  /**
   * AuthController service.
   * @module api/AuthControllerApi
   * @version 1.0
   */

  /**
   * Constructs a new AuthControllerApi. 
   * @alias module:api/AuthControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the loginUsingPOST operation.
     * @callback module:api/AuthControllerApi~loginUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * login
     * @param {String} user user
     * @param {module:api/AuthControllerApi~loginUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.loginUsingPOST = function(user, callback) {
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling loginUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
        'user': user,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/auth/login', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the signUpUsingPOST operation.
     * @callback module:api/AuthControllerApi~signUpUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/User} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * signUp
     * @param {module:model/RegistrationUser} authData authData
     * @param {module:api/AuthControllerApi~signUpUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/User}
     */
    this.signUpUsingPOST = function(authData, callback) {
      var postBody = authData;

      // verify the required parameter 'authData' is set
      if (authData === undefined || authData === null) {
        throw new Error("Missing the required parameter 'authData' when calling signUpUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = User;

      return this.apiClient.callApi(
        '/auth/register', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
