/*
 * CloneCord API
 * REST API to use CloneCord
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FormRole', 'model/Role'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/FormRole'), require('../model/Role'));
  } else {
    // Browser globals (root is window)
    if (!root.CloneCordApi) {
      root.CloneCordApi = {};
    }
    root.CloneCordApi.GuildRoleApi = factory(root.CloneCordApi.ApiClient, root.CloneCordApi.FormRole, root.CloneCordApi.Role);
  }
}(this, function(ApiClient, FormRole, Role) {
  'use strict';

  /**
   * GuildRole service.
   * @module api/GuildRoleApi
   * @version 1.0
   */

  /**
   * Constructs a new GuildRoleApi. 
   * @alias module:api/GuildRoleApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createRoleUsingPOST operation.
     * @callback module:api/GuildRoleApi~createRoleUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Role} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createRole
     * @param {String} guildId guildId
     * @param {module:model/FormRole} role role
     * @param {module:api/GuildRoleApi~createRoleUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Role}
     */
    this.createRoleUsingPOST = function(guildId, role, callback) {
      var postBody = role;

      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling createRoleUsingPOST");
      }

      // verify the required parameter 'role' is set
      if (role === undefined || role === null) {
        throw new Error("Missing the required parameter 'role' when calling createRoleUsingPOST");
      }


      var pathParams = {
        'guildId': guildId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = Role;

      return this.apiClient.callApi(
        '/guilds/{guildId}/roles', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteRoleUsingDELETE operation.
     * @callback module:api/GuildRoleApi~deleteRoleUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deleteRole
     * @param {String} guildId guildId
     * @param {String} roleId roleId
     * @param {module:api/GuildRoleApi~deleteRoleUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteRoleUsingDELETE = function(guildId, roleId, callback) {
      var postBody = null;

      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling deleteRoleUsingDELETE");
      }

      // verify the required parameter 'roleId' is set
      if (roleId === undefined || roleId === null) {
        throw new Error("Missing the required parameter 'roleId' when calling deleteRoleUsingDELETE");
      }


      var pathParams = {
        'guildId': guildId,
        'roleId': roleId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/guilds/{guildId}/roles/{roleId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateRoleUsingPUT operation.
     * @callback module:api/GuildRoleApi~updateRoleUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Role} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateRole
     * @param {String} guildId guildId
     * @param {module:model/FormRole} role role
     * @param {String} roleId roleId
     * @param {module:api/GuildRoleApi~updateRoleUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Role}
     */
    this.updateRoleUsingPUT = function(guildId, role, roleId, callback) {
      var postBody = role;

      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling updateRoleUsingPUT");
      }

      // verify the required parameter 'role' is set
      if (role === undefined || role === null) {
        throw new Error("Missing the required parameter 'role' when calling updateRoleUsingPUT");
      }

      // verify the required parameter 'roleId' is set
      if (roleId === undefined || roleId === null) {
        throw new Error("Missing the required parameter 'roleId' when calling updateRoleUsingPUT");
      }


      var pathParams = {
        'guildId': guildId,
        'roleId': roleId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['JWT'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = Role;

      return this.apiClient.callApi(
        '/guilds/{guildId}/roles/{roleId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
