/**
 * CloneCord API
 * REST API to use CloneCord
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FormGuild from '../model/FormGuild';
import Guild from '../model/Guild';

/**
* Guilds service.
* @module api/GuildsApi
* @version 1.0.7
*/
export default class GuildsApi {

    /**
    * Constructs a new GuildsApi. 
    * @alias module:api/GuildsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createGuild operation.
     * @callback module:api/GuildsApi~createGuildCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Guild} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new Guild
     * @param {Object} opts Optional parameters
     * @param {module:model/FormGuild} opts.formGuild 
     * @param {module:api/GuildsApi~createGuildCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Guild}
     */
    createGuild(opts, callback) {
      opts = opts || {};
      let postBody = opts['formGuild'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user-auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Guild;
      return this.apiClient.callApi(
        '/guilds', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteGuild operation.
     * @callback module:api/GuildsApi~deleteGuildCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes an owned Guild
     * @param {String} guildId ID of the specified Guild
     * @param {module:api/GuildsApi~deleteGuildCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteGuild(guildId, callback) {
      let postBody = null;
      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling deleteGuild");
      }

      let pathParams = {
        'guildId': guildId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user-auth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/guilds/{guildId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getGuildInfo operation.
     * @callback module:api/GuildsApi~getGuildInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Guild} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets info of a specific Guild
     * @param {String} guildId ID of the specified Guild
     * @param {module:api/GuildsApi~getGuildInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Guild}
     */
    getGuildInfo(guildId, callback) {
      let postBody = null;
      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling getGuildInfo");
      }

      let pathParams = {
        'guildId': guildId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user-auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Guild;
      return this.apiClient.callApi(
        '/guilds/{guildId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the kickMember operation.
     * @callback module:api/GuildsApi~kickMemberCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} guildId 
     * @param {String} memberId 
     * @param {module:api/GuildsApi~kickMemberCallback} callback The callback function, accepting three arguments: error, data, response
     */
    kickMember(guildId, memberId, callback) {
      let postBody = null;
      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling kickMember");
      }
      // verify the required parameter 'memberId' is set
      if (memberId === undefined || memberId === null) {
        throw new Error("Missing the required parameter 'memberId' when calling kickMember");
      }

      let pathParams = {
        'guildId': guildId,
        'memberId': memberId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user-auth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/guilds/{memberId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateGuild operation.
     * @callback module:api/GuildsApi~updateGuildCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Guild} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates an owned Guild
     * @param {String} guildId ID of the specified Guild
     * @param {module:model/FormGuild} formGuild New guild data
     * @param {module:api/GuildsApi~updateGuildCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Guild}
     */
    updateGuild(guildId, formGuild, callback) {
      let postBody = formGuild;
      // verify the required parameter 'guildId' is set
      if (guildId === undefined || guildId === null) {
        throw new Error("Missing the required parameter 'guildId' when calling updateGuild");
      }
      // verify the required parameter 'formGuild' is set
      if (formGuild === undefined || formGuild === null) {
        throw new Error("Missing the required parameter 'formGuild' when calling updateGuild");
      }

      let pathParams = {
        'guildId': guildId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['user-auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Guild;
      return this.apiClient.callApi(
        '/guilds/{guildId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
